#!/bin/bash

### Install packages ###
echo -e "Installing packages...\n"

yay -S --noconfirm \
swayfx swww waybar wlogout wofi xorg-xwayland \
ttf-jetbrains-mono-nerd noto-fonts-emoji ttf-font-awesome \
swappy grim slurp \
neofetch \
kitty ranger micro python-pillow \
bluez bluez-utils bluetuith \
pipewire-pulse pamixer 

### Copy Config Files ###
echo -e "Copying config files...\n"

cp -R sway ~/.config/
cp -R waybar ~/.config/
cp -R wofi ~/.config/
cp -R wlogout ~/.config/
cp -R kitty ~/.config/    

cp -R ranger ~/.config/
cp -R cava ~/.config/
cp -R neofetch ~/.config/
cp -R micro ~/.config/

### Script done ###
echo -e "Script had completed.\n"
