#!/bin/bash

### Install packages ####
echo -e "Installing packages...\n"

yay -S --noconfirm \
swayfx wofi swww waybar mako wlogout xorg-xwayland \
grim swappy slurp \
pipewire-pulse wireplumber \
bluez bluez-utils bluetuith \
ttf-jetbrains-mono-nerd noto-fonts-emoji ttf-font-awesome \
kitty neofetch micro ranger python-pillow \
firefox telegram-desktop-bin visual-studio-code-bin \
dotnet-host-bin dotnet-sdk-bin

### Enable bluetooth ###
echo -e "Starting the Bluetooth Service...\n"
sudo systemctl enable --now bluetooth.service

### Copy Config Files ###
echo -e "Copying config files...\n"

cp -R sway ~/.config/
cp -R waybar ~/.config/
cp -R wofi ~/.config/
cp -R wlogout ~/.config/
cp -R kitty ~/.config/    
cp -R mako ~/.config/
cp -R neofetch ~/.config/
cp -R micro ~/.config/

### Script is done ###
echo -e "Script had completed.\n"
