#! /bin/sh

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
RST="\e[0m"

#----config----
PROTOCOL="https"
SORT="rate"
#--------------

if [ "$EUID" -ne 0 ]
  then echo -e "${RED}Please run as root${RST}"
  exit
fi

if pacman -Qs reflector > /dev/null ; then
  echo "Updating mirrors for pacman..."
  sleep 1
  echo -e "${YELLOW}Type${RST}\t\tlatest"
  echo -e "${YELLOW}Protocol${RST}\t$PROTOCOL"
  echo -e "${YELLOW}Sort${RST}\t\t$SORT"

  reflector --latest $1 --protocol $PROTOCOL --sort $SORT --save /etc/pacman.d/mirrorlist
  echo -e "${GREEN}Script complete${RST}"
else
  echo -e "${RED}Reflector is not installed${RST}"
fi
